#!/bin/bash

if command -v starship &> /dev/null; then
    echo "Starship already installed ($(starship --version))"
else
    echo "Installing Starship..."
    curl -sS https://starship.rs/install.sh | sh -s -- -y
    echo "Starship installed!"
fi
# We put the 'eval "$(starship init zsh)"' line in .zshrc and not here to avoid issues

# Function to check if a font is installed
check_font_installed() {
    local font_name="$1"
    fc-list | grep -qi "$font_name"
}

# Install mise
curl https://mise.run | sh

echo "Installing global tools via Mise..."
mise install

# Install Homebrew Bundle
if [ -f "$HOME/.Brewfile" ]; then
    brew bundle --global
fi

echo "Bootstrap shell script executed!"
