#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
sort_by     = "natural"
show_hidden = true
scrolloff   = 10

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
